web:
  build: .docker/php
  environment:
    - ALLOW_OVERRIDE=true
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./app:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./data/db:/var/lib/mysql
  env_file:
    - ./.docker/secret/dev.env
  ports:
    - "8889:3306"