version: "3.1"
services:

  web:
    build: .docker/php
    container_name: amp-web
    volumes:
      - ./app:/var/www/html/
      - ./.docker/php/app.conf:/etc/apache2/sites-available/app.conf
      - ./.docker/php/app.conf:/etc/apache2/sites-enabled/app.conf
      - ./data/logs:/var/log/apache2
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mariadb
    container_name: amp-db
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./.docker/secret/dev.env
    ports:
      - "8890:3306"

networks:
  default:
    external:
      name: amp-base